### ISSUE TITLE
[BUG] Problem with running REDCapTideR script from crontab.  per error, Metadata not exported.

### ISSUE THREAD

**Issue by higgi13425** [CHOP-CGTInformatics/REDCapTidieR#215] opened 2024-12-04 10:48 UTC
# Expected Behavior
When I run the following script line by line (interactive), it works fine.
When I source it (sometimes it works, especially if I have just run it interactively line by line) 
or run from crontab (always it fails) on a schedule (desired behavior) it fails.

note that several other R and quarto scripts run from crontab on server with no issues.

script:

_library(tidyverse)
library(here)
library(janitor)
library(REDCapTidieR)

key <- Sys.getenv("REDCAP_KIRA_SGM_KEY")
redcap_url <- "https://redcapproduction.umms.med.umich.edu/api/"

datfr <- read_redcap(redcap_uri = redcap_url, token = key, suppress_redcapr_messages = FALSE)_

# Current Behavior
error message written to log:

The REDCap metadata export failed.  The http status code was 200.  The 'raw_text' returned was '

<!DOCTYPE HTML PUBLIC "-//W3C//Dtd HTML 4.0 transitional//en">

<html lang="en">
        <head>
                <META HTTP-EQUIV="expires" CONTENT="0">
        </head>
        <body>
                <script language="JavaScript">
                        
                </script>
        </body>
</html>
'.
Error in `read_redcap()`:
✖ The REDCapR export operation was not successful.
! An unexpected error occured.
ℹ This means that you probably discovered a bug!
ℹ Please consider submitting a bug report here:
  <https://github.com/CHOP-CGTInformatics/REDCapTidieR/issues>.
Caused by error in `redcap_metadata_read()`:
! The REDCap metadata export failed.  The http status code was 200.  The 'raw_text' returned was '

<!DOCTYPE HTML PUBLIC "-//W3C//Dtd HTML 4.0 transitional//en">

<html lang="en">
        <head>
                <META HTTP-EQUIV="expires" CONTENT="0">
        </head>
        <body>
                <script language="JavaScript">
                        
                </script>
        </body>
</html>
'.
Backtrace:
     ▆
  1. └─REDCapTidieR::read_redcap(redcap_uri = redcap_url, token = key, suppress_redcapr_messages = FALSE)
  2.   └─REDCapTidieR:::try_redcapr(...)
  3.     ├─rlang::catch_cnd(abort(out$outcome_message, call = calling_fn))
  4.     │ ├─rlang::eval_bare(...)
  5.     │ ├─base::tryCatch(...)
  6.     │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  7.     │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  8.     │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  9.     │ └─base::force(expr)
 10.     └─rlang::abort(out$outcome_message, call = calling_fn)
Execution halted

## How to Reproduce the Bug:
use script above, with local keys
rum on a schedule from crontab

**Screenshots**

## Failure Logs

The REDCap metadata export failed.  The http status code was 200.  The 'raw_text' returned was '

<!DOCTYPE HTML PUBLIC "-//W3C//Dtd HTML 4.0 transitional//en">

<html lang="en">
        <head>
                <META HTTP-EQUIV="expires" CONTENT="0">
        </head>
        <body>
                <script language="JavaScript">
                        
                </script>
        </body>
</html>
'.
Error in `read_redcap()`:
✖ The REDCapR export operation was not successful.
! An unexpected error occured.
ℹ This means that you probably discovered a bug!
ℹ Please consider submitting a bug report here:
  <https://github.com/CHOP-CGTInformatics/REDCapTidieR/issues>.
Caused by error in `redcap_metadata_read()`:
! The REDCap metadata export failed.  The http status code was 200.  The 'raw_text' returned was '

<!DOCTYPE HTML PUBLIC "-//W3C//Dtd HTML 4.0 transitional//en">

<html lang="en">
        <head>
                <META HTTP-EQUIV="expires" CONTENT="0">
        </head>
        <body>
                <script language="JavaScript">
                        
                </script>
        </body>
</html>
'.
Backtrace:
     ▆
  1. └─REDCapTidieR::read_redcap(redcap_uri = redcap_url, token = key, suppress_redcapr_messages = FALSE)
  2.   └─REDCapTidieR:::try_redcapr(...)
  3.     ├─rlang::catch_cnd(abort(out$outcome_message, call = calling_fn))
  4.     │ ├─rlang::eval_bare(...)
  5.     │ ├─base::tryCatch(...)
  6.     │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  7.     │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  8.     │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  9.     │ └─base::force(expr)
 10.     └─rlang::abort(out$outcome_message, call = calling_fn)
Execution halted

### Checklist
Before submitting this issue, please check and verify below that the submission meets the below criteria:

- [ ] The issue is atomic
- [ ] The issue description is documented
- [ ] The issue title describes the problem succinctly
- [ ] Developers are assigned to the issue
- [ ] Labels are assigned to the issue

**Comment by higgi13425** [comment] 2024-12-04 11:06
Note if I restart my R session, then try to Source the script, it fails the same way.
Somehow running this interactively works, and leaves some artifact that allows me to Source the script and it works, but in a clean, new session, it does not. I think that this might be a clue why the crontab sourcing is failing  - a clean, new runner environment on the server.

**Comment by higgi13425** [comment] 2024-12-04 11:11
note that I get a similar error in trying to run a different REDCapTidier Script from crontab:

this one says:
caused by error in `redcap_metadata_read`:
object 'ds' not found

and the trace looks similar to the other failure.

**Comment by higgi13425** [comment] 2024-12-04 17:07
this does run - with this output:

The data dictionary describing 540 fields was read from REDCap in 0.1 seconds.  The http status code was 200.
$data
# A tibble: 540 × 18
   field_name form_name    section_header field_type
   <chr>      <chr>        <chr>          <chr>     
 1 sbj_id     demographics NA             text      
 2 mrn        demographics NA             text      
 3 dob        demographics NA             text      
 4 zip        demographics NA             text      
 5 f_name     demographics NA             text      
 6 l_name     demographics NA             text      
 7 init       demographics NA             text      
 8 sbj_email  demographics NA             text      
 9 gender     demographics NA             dropdown  
10 race       demographics NA             checkbox  
# ℹ 530 more rows
# ℹ 14 more variables: field_label <chr>,
#   select_choices_or_calculations <chr>,
#   field_note <chr>,
#   text_validation_type_or_show_slider_number <chr>,
#   text_validation_min <chr>,
#   text_validation_max <chr>, identifier <chr>, …
# ℹ Use `print(n = ...)` to see more rows

$success
[1] TRUE

$status_code
[1] 200

$outcome_message
[1] "The data dictionary describing 540 fields was read from REDCap in 0.1 seconds.  The http status code was 200."

$forms_collapsed
[1] ""

$fields_collapsed
[1] ""

$elapsed_seconds
[1] 0.1348405

$raw_text
[1] ""

**Comment by higgi13425** [comment] 2024-12-04 17:09
When I restart R for a clean new session, this fails, with this output:

Error in REDCapR::redcap_metadata_read(redcap_uri = secret_url, token = secret_token) : 
  object 'ds' not found

**Comment by higgi13425** [comment] 2024-12-04 17:10
Not sure what the object 'ds' is in this case

**Comment by ezraporter** [comment] 2024-12-04 17:47
Got it. So things are failing under these same conditions or no?

> When I run the following script line by line (interactive), it works fine.
> When I source it (sometimes it works, especially if I have just run it interactively line by line)
> or run from crontab (always it fails) on a schedule (desired behavior) it fails.

**Comment by higgi13425** [comment] 2024-12-04 17:51
I'm afraid so. Same outcome with CRAN or dev version.
Running in a pristine environment always fails on the metadata

**Comment by ezraporter** [comment] 2024-12-04 17:57
Ah I see. That's very strange. The best place to start may be with a `REDCapR` issue since we rely on `REDCapR::redcap_metadata_read()` to get the metadata.

I'm going to close this issue for now but please feel free to reopen if you find a way to get `REDCapR::redcap_metadata_read()` to succeed and there are additional options we can expose to make that work in `REDCapTidieR`.

**Comment by skadauke** [comment] 2024-12-04 18:01
Have we ruled out that the issue is with the API key? Seems possible that in some environments it's defined and in others it isn't?

**Comment by higgi13425** [comment] 2024-12-05 10:41
API key is stored in r_environ on the server.
It would seem that restarting R would set up the link to r_environ.
But maybe not??
Will test

**Comment by higgi13425** [comment] 2024-12-05 10:55
OK, if I use this code, which explicitly puts the token into the script (on a firewalled server, but not best practice)

library(tidyverse)
library(janitor)
library(REDCapTidier)
library(here)

secret_key = "XXXXXXXXXXXX"
secret_url = "https://redcap.umich.edu/api/"

read_redcap(secret_url, secret_token)

AND I restart session before I Source it - it fails.

If I then immediately Source it again - it works.

When it fails - it is the usual

noisy tidyverse load
janitor load
here load

error in `redcap_metadata_read()`:
: object `ds` not found.

But, weirdly enough, Sourcing it a 2nd time (without restart) lets it find `ds` and run fine.
Is there a way to explicitly create ds, or tell it where to find ds early in the script??

**Comment by higgi13425** [comment] 2024-12-07 13:38
Working with Will on REDCapR - will try to get to the root of this.

**Comment by higgi13425** [comment] 2024-12-13 16:40
Following up on this with Will Beasley - we did a number of tests and determined that this is specific to the Michigan REDCap version. We did a debug and found a status code of 302.

 I talked to Andrew Carroll, our Michigan REDCap administrator today,
and the 302 status code was an important clue.

For complicated security reasons, API requests are redirected to a different website and then run.
Andrew confirmed that hitting this twice (with a short pause inbetween) from a cron job would allow access.

There will be a new more direct access URL available in early 2025.

So that this is a very odd, Michigan-specific REDCap problem.

Feel free to close this one now that we have a hacky work-around (ping/pause/ping) until the new URL is up.

**Comment by rsh52** [comment] 2024-12-13 16:42
Thanks for the update and keeping us in the loop, glad you were able to locate and semi-resolve the issue!

**Closed by rsh52** 2024-12-13 16:42 UTC
Labels: bug

**Comment by higgi13425** [comment] 2024-12-13 22:20
On a side note, I am now able to run (scheduled each AM on cron)

token = Sys.getenv("REDCap-project-key")
redcap_url = "https://redcap-ap-ps1a.med.mich.edu/api"

df <- REDCapTidieR::read_redcap(redcap_url, token)
d <- combine_checkboxes(
     supertbl = df,
      tbl = 'demographics',
      cols = starts_with('race'),
      multi_value_label = "Multiple",
      raw_or_label = "label",
      keep = TRUE)

demo <- d %>% pluck(3) %>% pluck(1)

demo %>%
  select(gender, ethnicity, race) %>%
  codified::table_nih_enrollment_pretty()

to get the 4th tab on https://phiggins.quarto.pub/longitudinal-stool-dashboard

entirely automated from REDCap, and
suitable for an annual NIH enrollment report.

Achievement unlocked.
